/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import Atxy2k.CustomTextField.RestrictedTextField;
import br.com.model.Dinheiro;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Lucas
 */
public final class VIEWmain extends javax.swing.JFrame {
    
    Dinheiro dinheiro = new Dinheiro();
    Font fontJText = new Font("Tahoma", Font.BOLD, 18);

    /**
     * Creates new form VIEWMani
     */
    public VIEWmain() {
        initComponents();
        initJTexts();
        validaSalario();
        initFonts();
        //invisibleContainer();
        //invisibleCifrao();
        //invisibleIcon();
        //invisibleLabel();
        //invisibleText();
    }
    
    public void initJTexts() {
        txtSalario.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.GRAY));
        txtDespesas.setBorder(null);
        txtLazer.setBorder(null);
        txtInvestimento.setBorder(null);
    }
    
    private void validaSalario() {
        RestrictedTextField validaTxtSalario = new RestrictedTextField(txtSalario);
        validaTxtSalario.setLimit(6);
        validaTxtSalario.setOnlyNums(true);
    }
    
    private void initFonts() {
        txtSalario.setFont(fontJText);
        txtDespesas.setFont(fontJText);
        txtLazer.setFont(fontJText);
        txtInvestimento.setFont(fontJText);
    }
    
    public void invisibleContainer() {
        lblContainerDespesas.setVisible(false);
        lblContainerLazer.setVisible(false);
        lblContainerInvestimento.setVisible(false);
    }
    
    public void invisibleIcon() {
        lblIconDespesas.setVisible(false);
        lblIconLazer.setVisible(false);
        lblIconInvestimento.setVisible(false);
    }
    
    public void invisibleCifrao() {
        lblCifrao2.setVisible(false);
        lblCifrao3.setVisible(false);
        lblCifrao4.setVisible(false);
    }
    
    public void invisibleLabel() {
        lblDespesas.setVisible(false);
        lblLazer.setVisible(false);
        lblInvestimento.setVisible(false);
    }
    
    public void invisibleText() {
        txtDespesas.setVisible(false);
        txtLazer.setVisible(false);
        txtInvestimento.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblIconSalario = new javax.swing.JLabel();
        lblIconDespesas = new javax.swing.JLabel();
        lblIconLazer = new javax.swing.JLabel();
        lblIconInvestimento = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        txtDespesas = new javax.swing.JTextField();
        txtLazer = new javax.swing.JTextField();
        txtInvestimento = new javax.swing.JTextField();
        panelFooter = new javax.swing.JPanel();
        lblPiggyBank = new javax.swing.JLabel();
        lblIfo = new javax.swing.JLabel();
        lblSalarioAtual = new javax.swing.JLabel();
        lblDespesas = new javax.swing.JLabel();
        lblLazer = new javax.swing.JLabel();
        lblInvestimento = new javax.swing.JLabel();
        lblCifrao2 = new javax.swing.JLabel();
        lblCifrao1 = new javax.swing.JLabel();
        lblCifrao3 = new javax.swing.JLabel();
        lblCifrao4 = new javax.swing.JLabel();
        lblContainerSalario = new javax.swing.JLabel();
        lblContainerDespesas = new javax.swing.JLabel();
        lblContainerLazer = new javax.swing.JLabel();
        lblContainerInvestimento = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        panelSalario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu dinheiro");
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(3, 139, 115));
        panelBackground.setLayout(null);

        lblIconSalario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Money.png"))); // NOI18N
        panelBackground.add(lblIconSalario);
        lblIconSalario.setBounds(210, 90, 40, 40);

        lblIconDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/MoneyTransation.png"))); // NOI18N
        panelBackground.add(lblIconDespesas);
        lblIconDespesas.setBounds(210, 170, 32, 40);

        lblIconLazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Summer.png"))); // NOI18N
        panelBackground.add(lblIconLazer);
        lblIconLazer.setBounds(210, 240, 32, 40);

        lblIconInvestimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Business.png"))); // NOI18N
        panelBackground.add(lblIconInvestimento);
        lblIconInvestimento.setBounds(210, 310, 30, 40);

        txtSalario.setBackground(new java.awt.Color(253, 250, 250));
        txtSalario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalarioKeyReleased(evt);
            }
        });
        panelBackground.add(txtSalario);
        txtSalario.setBounds(60, 105, 90, 25);

        txtDespesas.setEditable(false);
        txtDespesas.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.add(txtDespesas);
        txtDespesas.setBounds(60, 185, 90, 25);

        txtLazer.setEditable(false);
        txtLazer.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.add(txtLazer);
        txtLazer.setBounds(60, 255, 90, 25);

        txtInvestimento.setEditable(false);
        txtInvestimento.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.add(txtInvestimento);
        txtInvestimento.setBounds(60, 325, 90, 25);

        panelFooter.setBackground(new java.awt.Color(4, 130, 108));

        lblPiggyBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/PiggyBank48px.png"))); // NOI18N

        lblIfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/info.png"))); // NOI18N
        lblIfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblPiggyBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(lblIfo)
                .addGap(15, 15, 15))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPiggyBank))
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblIfo)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBackground.add(panelFooter);
        panelFooter.setBounds(0, 0, 270, 68);

        lblSalarioAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSalarioAtual.setText("Seu salário atual?");
        panelBackground.add(lblSalarioAtual);
        lblSalarioAtual.setBounds(30, 90, 93, 15);

        lblDespesas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDespesas.setText("Despesas");
        panelBackground.add(lblDespesas);
        lblDespesas.setBounds(30, 170, 60, 15);

        lblLazer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLazer.setText("Lazer");
        panelBackground.add(lblLazer);
        lblLazer.setBounds(30, 240, 30, 15);

        lblInvestimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInvestimento.setText("Investimento");
        panelBackground.add(lblInvestimento);
        lblInvestimento.setBounds(30, 310, 80, 15);

        lblCifrao2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCifrao2.setText("R$");
        panelBackground.add(lblCifrao2);
        lblCifrao2.setBounds(30, 185, 24, 20);

        lblCifrao1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCifrao1.setText("R$");
        panelBackground.add(lblCifrao1);
        lblCifrao1.setBounds(30, 105, 25, 22);

        lblCifrao3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCifrao3.setText("R$");
        panelBackground.add(lblCifrao3);
        lblCifrao3.setBounds(30, 255, 24, 22);

        lblCifrao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCifrao4.setText("R$");
        panelBackground.add(lblCifrao4);
        lblCifrao4.setBounds(30, 325, 30, 22);

        lblContainerSalario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Design.png"))); // NOI18N
        panelBackground.add(lblContainerSalario);
        lblContainerSalario.setBounds(15, 80, 240, 58);

        lblContainerDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Design.png"))); // NOI18N
        panelBackground.add(lblContainerDespesas);
        lblContainerDespesas.setBounds(15, 160, 240, 60);

        lblContainerLazer.setBackground(new java.awt.Color(255, 255, 255));
        lblContainerLazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Design.png"))); // NOI18N
        lblContainerLazer.setText("jLabel1");
        panelBackground.add(lblContainerLazer);
        lblContainerLazer.setBounds(15, 230, 240, 58);

        lblContainerInvestimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/image/Design.png"))); // NOI18N
        panelBackground.add(lblContainerInvestimento);
        lblContainerInvestimento.setBounds(15, 300, 240, 58);

        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        panelBackground.add(btnEnviar);
        btnEnviar.setBounds(20, 390, 230, 23);

        javax.swing.GroupLayout panelSalarioLayout = new javax.swing.GroupLayout(panelSalario);
        panelSalario.setLayout(panelSalarioLayout);
        panelSalarioLayout.setHorizontalGroup(
            panelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        panelSalarioLayout.setVerticalGroup(
            panelSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelBackground.add(panelSalario);
        panelSalario.setBounds(20, 90, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (txtSalario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Insira um salário");
        } else {
            dinheiro.setSalario(Float.parseFloat(txtSalario.getText()));
            dinheiro.administraSalario();
            mostraValores();
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void lblIfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIfoMouseClicked
        String mensagem = "Gerenciador Financeiro\n\n"
                + "1. Despesas (30%): "
                + "Para cobrir suas despesas mensais, como aluguel\n,"
                + " contas de serviços públicos e alimentação.\n\n"
                + "2. Lazer (50%): Reservado para atividades de "
                + "entretenimento e lazer, como restaurantes e "
                + "compras não essenciais.\n\n"
                + "3. Investimento/Reserva (20%): "
                + "Alocado para investir ou guardar, incluindo "
                + "contas de poupança e investimentos em ações.\n\n";
        JOptionPane.showMessageDialog(this, mensagem, "Info", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_lblIfoMouseClicked

    private void txtSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyReleased

    }//GEN-LAST:event_txtSalarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEWmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new VIEWmain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblCifrao1;
    private javax.swing.JLabel lblCifrao2;
    private javax.swing.JLabel lblCifrao3;
    private javax.swing.JLabel lblCifrao4;
    private javax.swing.JLabel lblContainerDespesas;
    private javax.swing.JLabel lblContainerInvestimento;
    private javax.swing.JLabel lblContainerLazer;
    private javax.swing.JLabel lblContainerSalario;
    private javax.swing.JLabel lblDespesas;
    private javax.swing.JLabel lblIconDespesas;
    private javax.swing.JLabel lblIconInvestimento;
    private javax.swing.JLabel lblIconLazer;
    private javax.swing.JLabel lblIconSalario;
    private javax.swing.JLabel lblIfo;
    private javax.swing.JLabel lblInvestimento;
    private javax.swing.JLabel lblLazer;
    private javax.swing.JLabel lblPiggyBank;
    private javax.swing.JLabel lblSalarioAtual;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelSalario;
    private javax.swing.JTextField txtDespesas;
    private javax.swing.JTextField txtInvestimento;
    private javax.swing.JTextField txtLazer;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables

    private void mostraValores() {
        String formatoMonetario = "%.2f";
        txtDespesas.setText(Float.toString(dinheiro.getGastoFixo()).format(formatoMonetario, dinheiro.getGastoFixo()));
        txtLazer.setText(Float.toString(dinheiro.getGastoVariavel()).format(formatoMonetario, dinheiro.getGastoVariavel()));
        txtInvestimento.setText(Float.toString(dinheiro.getFundoMonetario()).format(formatoMonetario,dinheiro.getFundoMonetario()));
    }
    
}
